### ISSUE TITLE
Зачем столько раз округлять?

### ISSUE THREAD

**Issue by coursar** [ShamilTim/Lecture_2_Homework#2]
https://github.com/ShamilTim/Lecture_2_Homework/blob/2c3f097993139d08c6b8f3a25e86701a4e139279/lib.py#L13-L16

**Comment by ShamilTim** [comment]
Для того чтобы получить наиболее точное значение необходимого числа рулонов. Проверил: при расчете различных сочетаний параметров на входе без округления, существует возможность ошибиться на +- 1 рулон.
